### ISSUE TITLE
no data stored in DB

### ISSUE THREAD

**Issue by nl2299** [coderpussy/SolarTherm-WIFI-Local-Admin#1]
First of great project, beautiful ui and relativly simple. I know docu is still in process.
For my test install i used a PI with LAMP stack as suggested, followed the instrustions.
Created a user called solartherm to access the DB. All good so far. Adjusted several config files.
Uploaded the sketch to an ESP without an BME connected...
on serial output all looks fine
`Initializing serial connection DONE.
Initializing connection to the network with MAC address CC:50:XX:XX:XX:XX using WiFiManager (SSID: myWIFI)...
*WM: 
*WM: AutoConnect
*WM: Connecting as wifi client...
*WM: Status:
*WM: 6
*WM: Using last saved values, should be faster
*WM: Connection result: 
*WM: 3
*WM: IP Address:
*WM: 192.168.100.123
DONE. IP address: 192.168.100.123 MAC address: CC:50:XX:XX:XX:XX
Initializing LocalStorage client to host http://192.168.100.124/admin...DONE.
Initializing MagicMirror client to host http://192.168.100.124:8080...DONE.
Initializing the temperature sensor...BME280: Could not find a valid BME280 sensor, check wiring!
SensorID was: 0xFF
DONE.
Reset reason: Deep-Sleep Wake
Application version: 0.0.1
Setup completed.
Initializing Over-The-Air Updater...Update Error (-102): File Not Found (404)
DONE.
Measuring...
Reading sensor data... DONE.
Temperature: 0.0 °C
Humidity: 0.0 %
Pressure: 0.0 hPa
Altitude: 44330.0 m
Reading battery voltage... 0.01V DONE.
Sending data to LocalStorage...
LocalStorageClient: Sending POST request to LocalStorage at http://192.168.100.124/admin/remote-temperature.php
LocalStorageClient: HTTP request body: { "apikey": "mysupersecretkey", "name": "livingroom", "temperature": "0.00", "humidity": "0.00", "pressure": "0.00", "altitude": "44330.00", "battery": "0.01" }
LocalStorageClient: Received HTTP status code: 200
DONE.
Sending data to MagicMirror...
MagicMirrorClient: Sending POST request to MagicMirror at http://192.168.100.234:8080/remote-temperature
MagicMirrorClient: HTTP request body: { "temp": 0, "humidity": 0, "battery": -200, "sensorId": "livingroom" }
MagicMirrorClient: Received HTTP status code: -1
MagicMirrorClient: Received HTTP response body: 
DONE.
Measuring: DONE.
Going to Deep-Sleep for 600 seconds...`

For me values (even no sensor connected) submitted successfully to the  remote-temperature.php script. (of course all related files located in /admin) Im not using magic mirror for first test i leave it there.
If check the web-page all graphs and bar displaying no data.  The get-data.php displays a blank page ( at beginning, before i created the solartherm user it says something like "no permissions no access" whatever.

Database itself is empty checked with sql command
**select * from solartherm.sensors;**
Empty set (0.001 sec)

any help is appreciated. Thanks!

**Comment by coderpussy** [comment]
Hi. It seems that you forgot to enter the password hash (API key) in your Arduino sketch config.h. To make a valid password i provide the file `generate-password.php`. The generated password hash is the API key. The API key is almost 60 signs long.

**Comment by nl2299** [comment]
yes i created the api key with the generate_password.php file, it displays a 60 digits code i pasted in remote-temperature.php under` $password = '60digitsKey'; // password salt for password_hash` as well as in the config.h at `const char* LOCAL_STORAGE_API_KEY = "60digitsKey";` So on both ends i use these generated api key

**Comment by coderpussy** [comment]
In the `remote-temperature.php` you have to set the String you used for generating the API key.

**Comment by nl2299** [comment]
got it. entered the string in the `remote-temperature.php` file and the API key (60 digits) only in the config.h
I still getting no values on the DB or frontend. As the `get-data.php` does not report any error i think the connection and auth. is working :/ In case of a successful data transmission is there anything else to to instead of reload the frontent (website) ? Or maybe these happens because no sensor connected ? Thanks for answering my basic questions.

**Comment by coderpussy** [comment]
Access rights to the files? All the folder and files are executable by webserver user and group? What happens if you call the URL you configured in the Sketch directly in browser? Something like this:
`http://192.168.100.124/admin/remote-temperature.php`
Should show a white blank page without any errors.

**Comment by nl2299** [comment]
i also moved the files located in admin folder to the root of `/var/www/` set rights to 777 and also try to change the owner from `pi` to `www-data` - all this steps change nothing.
scripts `http://192.168.100.124/remote-temperature.php` and `http://192.168.100.124/get-data`  respond with a blank page, no error.

**Comment by coderpussy** [comment]
Sketch URL to local storage also adjusted (removed admin)? Maybe php.ini settings (allow_url_fopen)?

**Comment by nl2299** [comment]
yep scetch url adjusted, php ini file included `allow_url_fopen = On`  so these settings look correct
The LAMP installation is completely untouched.

**Comment by coderpussy** [comment]
It depends where you have configured your webserver log files. You can inspect them e.g.:
`sudo tail -f /var/log/apache2/error.log` or `sudo tail -f /var/log/apache2/access.log`. Or cat the content directly.

The POST request should be in the acces.log and looks similar to this if everything is okay:
`"POST /remote-temperature.php HTTP/1.1" 200 207 "-" "ESP8266HTTPClient"`

If something goes strange it should appear in the webserver error.log

**Comment by nl2299** [comment]
I got 2 entrys in the access.log when i reset the esp
`[09/Mar/2021:21:07:38 +0000] "GET /solartherm-ota/ota-update.php HTTP/1.0" 200 225 "-" "ESP8266-http-Update"
[09/Mar/2021:21:07:38 +0000] "POST /remote-temperature.php HTTP/1.1" 200 424 "-" "ESP8266HTTPClient"`
At the time i reload the webpage i also got:
`[09/Mar/2021:21:06:07 +0000] "GET / HTTP/1.1" 200 1755 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36"
 [09/Mar/2021:21:06:07 +0000] "GET /get-data.php?device=Wohnzimmer HTTP/1.1" 200 204 "http://192.168.178.69/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36"`
In the error.log it only prints out errors related to the ota-functionality which is not used
`[Tue Mar 09 21:12:19.316602 2021] [php7:notice] [pid 1036] [client 192.168.100.100:52682] PHP Notice:  Undefined index: CC:50:E3:C7:4E:6E in /var/www/html/solartherm-ota/ota-update.php on line 55
[Tue Mar 09 21:12:19.318569 2021] [php7:warn] [pid 1036] [client 192.168.100.100:52682] PHP Warning:  md5_file(./bin/.bin): failed to open stream: No such file or directory in /var/www/html/solartherm-ota/ota-update.php on line 60
[Tue Mar 09 21:12:19.320686 2021] [php7:warn] [pid 1036] [client 192.168.100.100:52682] PHP Warning:  filesize(): stat failed for ./bin/.bin in /var/www/html/solartherm-ota/ota-update.php on line 21
[Tue Mar 09 21:12:19.323066 2021] [php7:warn] [pid 1036] [client 192.168.100.100:52682] PHP Warning:  md5_file(./bin/.bin): failed to open stream: No such file or directory in /var/www/html/solartherm-ota/ota-update.php on line 22
[Tue Mar 09 21:12:19.325015 2021] [php7:warn] [pid 1036] [client 192.168.100.100:52682] PHP Warning:  readfile(./bin/.bin): failed to open stream: No such file or directory in /var/www/html/solartherm-ota/ota-update.php on line 23`

**Comment by coderpussy** [comment]
Okay. Let's take a look closer to this problem. First, to avoid any interruption uncomment line 83, 91, 196-198 in your Sketch ino file. Your line numbers might be different if you changed something in the ino. This disable the MagicMirror and OTA Updater clients execution. Of course, you have to flash the Wemos new.

After this the PHP warnings related to OTA Updater in your apache log will disappear. If this is still not working, the remote-temperature.php might be the problem. Let's see.

**Comment by nl2299** [comment]
yes the error messages disappeared after adjusting the sketch. In acess log all looking still good
`"POST /remote-temperature.php HTTP/1.1" 200 424 "-" "ESP8266HTTPClient"`
But no data will arrive at the server, db still empty.
i use mariaDB instead of mysql - does this matter ?

**Comment by coderpussy** [comment]
I also use mariaDB. You can set debug in your sketch ino (line 105) to true. Maybe there is some more information about transfer. Next, you can add `var_dump($json);` in line 4 after the php input stream inside `remote-temperature.php`. This should add the output from var_dump into your apache log file. Instead of just var_dump this you can add an additional file piping after var_dump with:
`$fp = file_put_contents('server.log', $json);
die();` <- this puts json data, if available, into server.log file and makes sure that no further execution will happen.
If everything goes well you have some more information about whats going on in your apache log or additional var_dump log file.

**Comment by nl2299** [comment]
enable the debug in sketch - i didn't get any additional information's looks as before.
I tried adding `var_dump($json);` in `remote_temperature.php` nothing additional in access or error.log
If i load the `remote-temperature.php` in the browser i got `string(0) ""` so a syntax error ? idk. Also tried the same with` $fp = file_put_contents('server.log', $json); die();` - blank page no error... but also no `server.log` generated.
First block of the `remote-temperature.php` file
 ```
<?php
    // Get json stream content
    $json = file_get_contents('php://input');
    $fp = file_put_contents('server.log', $json); die();
    if(!empty($json)) {
        // Decode json string
        $obj = json_decode($json);
```

**Comment by coderpussy** [comment]
Hm, it sounds that `remote-temperature.php` received nothing from the wemos. But beside a lot of possible issues this can happen if the sended json string is invalid. And probably the most produced issue either.
But also other issues are highly possible. Firewalls, PHP version, DB version, Apache version. What is executable and what forbidden by webserver and so on and so on. php.ini file is also important and maybe the issue is related to this file.

Just a sidenote, the files `remote-temperature.php` and `get-data.php` are normally not called directly over webbrowser. They are used by scripts and not by human. There are several conditions to avoid direct calling and executing. Normally you have to wait the given deep sleep time and look into your Arduino serial console after awaking. Just milliseconds later there should appear the POST request with json header and of course given data (doesn't matter if the values are 0) in your tail -f webserver logs (access and error) on your RPi LAMP.

I developed this on LAMP Stack side with:
System: Raspbian GNU/Linux 9 (stretch)
Apache 2:  Apache/2.4.25 (Raspbian)
PHP: PHP Version 7.2.34
MariaDB Server-Version: 10.1.48
DB Client Version: libmysql - mysqlnd 5.0.12

Only thing is that i installed the PHP from https://packages.sury.org/php
A first address of what you can await is here:
https://www.itzgeek.com/how-tos/linux/debian/how-to-install-php-7-3-7-2-7-1-on-debian-10-debian-9-debian-8.html

Furthermore you can add a php file (info.php) to your webroot with following content:
`<?php
phpinfo();`
And call the file to make the PHP configuration visible e.g.: `http://192.168.100.124/info.php` or where your webroot is located.

**Comment by nl2299** [comment]
Mh i found the server.log (looked in wrong dir :D) and i got the right values ... so transmission is possible
`{ "apikey": "60digits", "name": "Wohnzimmer", "temperature": "0.00", "humidity": "0.00", "pressure": "0.00", "altitude": "44330.00", "battery": "0.01" }`
Thats exactly the same as the wemos serial output
software version:
php version is 7.3 
Apache/2.4.38 (Raspbian)
10.3.27-MariaDB-0+deb10u1 Raspbian 10

**Comment by coderpussy** [comment]
Okay. Data was received, great. Next is to check if you can pass the password verify. Remove the added part in line 4 and add this to line 20 `$fp = file_put_contents('server.log', 'password checked');`. After that add to line 28 `$fp = file_put_contents('server.log', 'db connection ready');`. Finally after that check just before inserting into database in line 42 `$fp = file_put_contents('server.log', 'insert data');`

**Comment by nl2299** [comment]
ok 
`$fp = file_put_contents('server.log', 'password checked'); ` result password checked
`$fp = file_put_contents('server.log', 'db connection ready');` result db connection ready
`$fp = file_put_contents('server.log', 'insert data');` result insert data
just sends the data in ' ' back.

**Comment by coderpussy** [comment]
Okay. I think i got it. You used the `solartherm.sql` file to create the database, right? In this Script is a bug. Or a miss by me. I exported the database structure without auto increment key. If this is not done on your solartherm database sensors table this should add a auto increment key to the id field.
```sql
ALTER TABLE sensors MODIFY id int(6) UNSIGNED NOT NULL AUTO_INCREMENT;
```

**Comment by coderpussy** [comment]
Next pitfall could be the `LOCAL_STORAGE_HOSTNAME` in your ino sketch `config.h` file. It depends what you have entered here.
Didn't changed means you have to adjust the `id` in line 25 and 26 inside `index.html`.
If you just use one device than delete line 26 and add the name from the sketch in line 25 e.g.:
```html
<li><span id="livingroom">Livingroom</span></li>
```

**Comment by nl2299** [comment]
on my side the `LOCAL_STORAGE_HOSTNAME` is `Wohnzimmer` also in the index
```
                <li><span id="Wohnzimmer">Wohnzimmer</span></li>
                <!--<li><span id="Schlafzimmer">Schlafzimmer</span></li>-->
```
added the key in the database the sensors table looks like that:
```
MariaDB [solartherm]> SHOW COLUMNS from sensors;
+-------------+-----------------+------+-----+---------------------+-------------------------------+
| Field       | Type            | Null | Key | Default             | Extra                         |
+-------------+-----------------+------+-----+---------------------+-------------------------------+
| id          | int(6) unsigned | NO   | PRI | NULL                | auto_increment                |
| name        | varchar(50)     | YES  |     | NULL                |                               |
| temperature | varchar(30)     | YES  |     | NULL                |                               |
| pressure    | varchar(30)     | YES  |     | NULL                |                               |
| altitude    | varchar(30)     | YES  |     | NULL                |                               |
| humidity    | varchar(30)     | YES  |     | NULL                |                               |
| battery     | varchar(30)     | YES  |     | NULL                |                               |
| Date        | date            | YES  |     | NULL                |                               |
| Time        | time            | YES  |     | NULL                |                               |
| TimeStamp   | timestamp       | YES  |     | current_timestamp() | on update current_timestamp() |
+-------------+-----------------+------+-----+---------------------+-------------------------------+
10 rows in set (0.031 sec)
```
db has still no data received / written  :/

**Comment by coderpussy** [comment]
The only difference to my table is that i have no `NULL` value at the default column for field `id`. But as far as i read this shouldn't be a problem.  Maybe try to delete the database and recreate. I provided a new database structure sql dump `solartherm.sql`.

**Comment by nl2299** [comment]
i really have no idea whats wrong here,
also DROP DATABASE and use the updated solartherm.sql does not help here.

**Comment by coderpussy** [comment]
Just guessing, but have your setted up DB user the correct access rights to write into the solartherm database?

**Comment by nl2299** [comment]
```
| Grants for solartherm@localhost

| GRANT ALL PRIVILEGES ON *.* TO `solartherm`@`localhost` IDENTIFIED BY PASSWORD '*873B8EA21A3BB97C91D32209139CF393A70423F3' WITH GRANT OPTION |
| GRANT ALL PRIVILEGES ON `solartherm`.* TO `solartherm`@`localhost`
                       |
| GRANT ALL PRIVILEGES ON `solartherm`.`sensors` TO `solartherm`@`localhost`
```
                       
when the user permissions are wrong, shouldn't the remote-temperature.php print a error message, for failed connection ?

**Comment by coderpussy** [comment]
Yes, connection should die.
Maybe try to insert a data row manually on mysql console.
```sql
INSERT INTO sensors (id,name, temperature, humidity, pressure, altitude, battery, Date, Time) VALUES (1,'Wohnzimmer','20.00','1000.00','30.00','50.00','3.50','2021-03-12','17:00:00');
```
I read that maybe mysql can have a issue if the initial auto increment value is not set. Manually inserting can solve the issue further. Other's have good results with removing and adding back auto increment on that column. Another possible solution might be a alter on that table.
```sql
ALTER TABLE sensors AUTO_INCREMENT=1;
```
You can also let show up the auto increment value for that table.
```sql
SHOW TABLE STATUS LIKE 'sensors';
```
If result is a auto increment value of 0 than there is a bug and try to alter or insert data manually. After manually inserting data wait 10 minutes or what you have configured and look if something is changing.

**Comment by coderpussy** [comment]
I provided a new `solartherm.sql` file.

**Comment by nl2299** [comment]
Surprise surprise 🎉🎉
ITS FINALLY WORKING 
I just added a row with data manually - after that the website displays this data and also receives data from esp every 10 mins or on reset.
Will it Test some hours.
Working fine in chrome 
On safari (mobile and desktop) the last update field just displays `InvaildDate invalidDate` But I don’t want complain ☺️

**Comment by coderpussy** [comment]
:raised_hands: As i wrote, is deep early dev state. :yum: But i'm always interested in having some feedback to make things better. :relaxed:
